### ISSUE TITLE
Drop support for V2 of glances server

### ISSUE THREAD

**Issue by engrbm87** [home-assistant-ecosystem/python-glances-api#25]
With more data keys being added to this api we are not considering if these keys are available in both V2 and V3 of Glances. Example issue (https://github.com/home-assistant/core/issues/99735).
Should we drop support for V2 or should we implement a check for the specified version when adding new data keys.

cc @fabaff

**Comment by fabaff** [comment]
I guess that it would be the simplest way to drop support for V2.
